### ISSUE TITLE
QuoteItem interval option value is set to null when customer tries to make a reorder

### ISSUE THREAD

**Issue by kamilcanary** [subscribepro/subscribepro-magento2-ext#156]
When the existing order has items with subscriptions and customer tries to make a reorder in My Account - interval option value on the QuoteItem is set to null. I believe the issue happens in this method:
`\Swarming\SubscribePro\Model\Quote\SubscriptionOption\Updater::update` when param $itemAddedBySubscribePro is set to true.

Magento version: 2.4.5-p1
SubscribePro module version: 1.5.16

**Comment by chrismshea** [comment]
Attaching screenshots from initial request.

![CleanShot 2022-12-02 at 11 59 55@2x](https://user-images.githubusercontent.com/1232258/205925716-686307d5-2b3a-421b-8f9f-97163bb8acbd.png)
![CleanShot 2022-12-02 at 11 58 32@2x](https://user-images.githubusercontent.com/1232258/205925757-24e7658f-abb4-42c5-b670-fe9cf323b21f.png)

**Comment by czettnersandor** [comment]
I can see why it's happening, could you confirm what steps are required to reproduce this error? The logic behind it is to set the interval to null at the end of checkout, that should not be changed, so it's correct, but I can't see any way to reorder from the my account page.

**Comment by vetalkab** [comment]
@czettnersandor 
While it is still possible to place the order when the user chooses the interval in the cart the system.log file is full of errors:
`[2022-11-17T11:08:12.550577+00:00] report.CRITICAL: TypeError: Project\SubscribeProInterval\Helper\Interval::getDiscountByInterval(): Argument #2 ($subscriptionInterval) must be of type string, null given, called in /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/app/code/Project/SubscribeProInterval/Model/Quote/ItemSubscriptionDiscount.php on line 72 and defined in /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/app/code/Project/SubscribeProInterval/Helper/Interval.php:86
Stack trace:
#0 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/app/code/Project/SubscribeProInterval/Model/Quote/ItemSubscriptionDiscount.php(72): Project\SubscribeProInterval\Helper\Interval->getDiscountByInterval()
#1 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/app/code/Project/SubscribeProInterval/Model/Quote/ItemSubscriptionDiscount.php(56): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount->updateProductDiscount()
#2 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/subscribepro/subscribepro-magento2-ext/Model/Quote/ItemSubscriptionDiscount.php(70): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount->getPlatformProduct()
#3 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Swarming\SubscribePro\Model\Quote\ItemSubscriptionDiscount->processSubscriptionDiscount()
#4 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount\Interceptor->___callParent()
#5 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/project/magento2-subscribepro-trial/Plugin/SubscribePro/Model/Quote/ItemSubscriptionDiscountPlugin.php(61): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): FindCanary\SubscribeProTrial\Plugin\SubscribePro\Model\Quote\ItemSubscriptionDiscountPlugin->aroundProcessSubscriptionDiscount()
#7 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Project/SubscribeProInterval/Model/Quote/ItemSubscriptionDiscount/Interceptor.php(23): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount\Interceptor->___callPlugins()
#9 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/subscribepro/subscribepro-magento2-ext/Plugin/SalesRule/Validator.php(99): Project\SubscribeProInterval\Model\Quote\ItemSubscriptionDiscount\Interceptor->processSubscriptionDiscount()
#10 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Swarming\SubscribePro\Plugin\SalesRule\Validator->aroundProcess()
#11 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Zonos\Checkout\Model\Discount\Validator\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Zonos/Checkout/Model/Discount/Validator/Interceptor.php(23): Zonos\Checkout\Model\Discount\Validator\Interceptor->___callPlugins()
#13 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-sales-rule/Model/Quote/Discount.php(190): Zonos\Checkout\Model\Discount\Validator\Interceptor->process()
#14 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/zonos/checkout/Model/Discount/Discount.php(22): Magento\SalesRule\Model\Quote\Discount->collect()
#15 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(261): Zonos\Checkout\Model\Discount\Discount->collect()
#16 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals()
#17 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callParent()
#18 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/amasty/promo/Plugin/Quote/Model/Quote/TotalsCollectorPlugin.php(132): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Promo\Plugin\Quote\Model\Quote\TotalsCollectorPlugin->aroundCollectAddressTotals()
#20 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Quote/Model/Quote/TotalsCollector/Interceptor.php(41): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callPlugins()
#22 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(156): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->collectAddressTotals()
#23 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote\TotalsCollector->collect()
#24 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callParent()
#25 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Quote/Model/Quote/TotalsCollector/Interceptor.php(32): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callPlugins()
#27 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-quote/Model/Quote.php(2024): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->collect()
#28 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote->collectTotals()
#29 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\Interceptor->___callParent()
#30 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-deferred-total-calculating/Plugin/TotalsCollectorPlugin.php(137): Magento\Quote\Model\Quote\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Magento\DeferredTotalCalculating\Plugin\TotalsCollectorPlugin->aroundCollectTotals()
#32 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Quote\Interceptor->Magento\Framework\Interception\{closure}()
#33 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Quote/Model/Quote/Interceptor.php(68): Magento\Quote\Model\Quote\Interceptor->___callPlugins()
#34 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(121): Magento\Quote\Model\Quote\Interceptor->collectTotals()
#35 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteRepository\SaveHandler->save()
#36 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteRepository\SaveHandler\Interceptor->___callParent()
#37 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\SaveHandler\Interceptor->Magento\Framework\Interception\{closure}()
#38 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Quote/Model/QuoteRepository/SaveHandler/Interceptor.php(23): Magento\Quote\Model\QuoteRepository\SaveHandler\Interceptor->___callPlugins()
#39 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-quote/Model/QuoteRepository.php(202): Magento\Quote\Model\QuoteRepository\SaveHandler\Interceptor->save()
#40 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteRepository->save()
#41 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteRepository\Interceptor->___callParent()
#42 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}()
#43 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(50): Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins()
#44 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-sales/Model/Reorder/Reorder.php(164): Magento\Quote\Model\QuoteRepository\Interceptor->save()
#45 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-sales/Controller/AbstractController/Reorder.php(87): Magento\Sales\Model\Reorder\Reorder->execute()
#46 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\AbstractController\Reorder->execute()
#47 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent()
#48 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-async-order/Plugin/Controller/Order/CustomerRedirectPlugin.php(104): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#49 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Magento\AsyncOrder\Plugin\Controller\Order\CustomerRedirectPlugin->aroundExecute()
#50 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#51 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(23): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins()
#52 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Order\Reorder\Interceptor->execute()
#53 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#54 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent()
#55 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(32): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins()
#57 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Order\Reorder\Interceptor->dispatch()
#58 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#59 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#60 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#61 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#62 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#63 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#64 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#65 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#66 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#67 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#68 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#69 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#70 /var/www/releases/34bc9a236a9d063ffcdfab4419822f7d1d2243e6299/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#71 {main} [] []`

**Comment by czettnersandor** [comment]
Yes, I can see what you mean now. And also, if I select subscription at this point in the cart, it's not getting forwarded or handled as a subscription at all. I'm investigating.

**Comment by garthbrantley** [comment]
@chrismshea Can you document steps to reproduce if this still occurs?
