### ISSUE TITLE
Fix: "Current customer does not have an active cart."

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#222]
This is possibly a local install issue.

Im getting:

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/c2a249f7-6a65-466c-b890-a293d39844f1)

```txt
{message: "Current customer does not have an active cart.",…}
message
:
"Current customer does not have an active cart."
trace
:
"#0 /var/www/html/generated/code/Magento/Quote/Model/Webapi/ParamOverriderCartId/Proxy.php(95): Magento\\Quote\\Model\\Webapi\\ParamOverriderCartId->getOverriddenValue()\n
#1 /var/www/html/vendor/magento/module-webapi/Controller/Rest/ParamsOverrider.php(64): Magento\\Quote\\Model\\Webapi\\ParamOverriderCartId\\Proxy->getOverriddenValue()\n
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest\\ParamsOverrider->override(Array, Array)\n
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\ParamsOverrider\\Interceptor->___callParent('override', Array)\n
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\ParamsOverrider\\Interceptor->Magento\\Framework\\Interception\\{closure}(Array, Array)\n
#5 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/ParamsOverrider/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\ParamsOverrider\\Interceptor->___callPlugins('override', Array, Array)\n
#6 /var/www/html/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(146): Magento\\Webapi\\Controller\\Rest\\ParamsOverrider\\Interceptor->override(Array, Array)\n
#7 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(32): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->getInputData()\n
#8 /var/www/html/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(115): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->getInputData()\n
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()\n
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->___callParent('resolve', Array)\n
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n
#12 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->___callPlugins('resolve', Array, Array)\n
#13 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->resolve()\n
#14 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(202): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#18 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n
#19 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#20 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http->launch()\n
#21 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()\n
#22 /var/www/html/pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
#23 {main}"
```

**Comment by garthbrantley** [comment]
Possibly a local dev environment issue.
