### ISSUE TITLE
Class 'array' Does Not Exist when attempting to access SOAP endpoints after SP extension is installed

### ISSUE THREAD

**Issue by imkingdavid** [subscribepro/subscribepro-magento2-ext#28]
I am able to reproduce this in multiple M2 environments with the SP extension installed.

Steps to reproduce:

1. Install M2 and the SP extension.
2. Navigate to `https://{DOMAIN}/soap/default/?wsdl&services=catalogProductRepositoryV1`
3. If error reporting is not disabled you will see:
`Internal Error. Details are available in Magento log file. Report ID: webapi-58f678b12b20b`
(Otherwise you will find that in a file in var/report).
4. When you look in the var/log/exception.log file you will find the following:
```
[2017-04-18 20:36:01] main.CRITICAL: exception 'LogicException' with message 'Class "array" does not exist. Please note that namespace must be specified.' in /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php:156
Stack trace:
#0 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(229): Magento\Framework\Reflection\TypeProcessor->register('array')
#1 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(198): Magento\Framework\Reflection\TypeProcessor->_processMethod(Object(Zend\Code\Reflection\MethodReflection), 'SwarmingSubscri...')
#2 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Swarming\\Subsc...')
#3 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(229): Magento\Framework\Reflection\TypeProcessor->register('\\Swarming\\Subsc...')
#4 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(198): Magento\Framework\Reflection\TypeProcessor->_processMethod(Object(Zend\Code\Reflection\MethodReflection), 'SwarmingSubscri...')
#5 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Swarming\\Subsc...')
#6 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(183): Magento\Framework\Reflection\TypeProcessor->register('\\Swarming\\Subsc...')
#7 /var/www/html/web/magento2test/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Swarming\\Subsc...')
#8 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/Config/ClassReflector.php(103): Magento\Framework\Reflection\TypeProcessor->register('\\Swarming\\Subsc...')
#9 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection))
#10 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/ServiceMetadata.php(120): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('Swarming\\Subscr...', Array)
#11 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/ServiceMetadata.php(148): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata()
#12 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/ServiceMetadata.php(165): Magento\Webapi\Model\ServiceMetadata->getServicesConfig()
#13 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(366): Magento\Webapi\Model\ServiceMetadata->getServiceMetadata('catalogProductR...')
#14 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(169): Magento\Webapi\Model\Soap\Wsdl\Generator->getServiceMetadata('catalogProductR...')
#15 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(374): Magento\Webapi\Model\AbstractSchemaGenerator->getAllowedServicesMetadata(Array)
#16 /var/www/html/web/magento2test/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(104): Magento\Webapi\Model\Soap\Wsdl\Generator->getAllowedServicesMetadata(Array)
#17 /var/www/html/web/magento2test/vendor/magento/module-webapi/Controller/Soap.php(132): Magento\Webapi\Model\AbstractSchemaGenerator->generate(Array, 'https', 'davidking.io', 'https://davidki...')
#18 /var/www/html/web/magento2test/var/generation/Magento/Webapi/Controller/Soap/Interceptor.php(24): Magento\Webapi\Controller\Soap->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/web/magento2test/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Soap\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/web/magento2test/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#21 /var/www/html/web/magento2test/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#22 {main}

Next exception 'Exception' with message 'Report ID: webapi-58f678b12b20b; Message: Class "array" does not exist. Please note that namespace must be specified.' in /var/www/html/web/magento2test/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/html/web/magento2test/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /var/www/html/web/magento2test/var/generation/Magento/Framework/Webapi/ErrorProcessor/Proxy.php(95): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /var/www/html/web/magento2test/vendor/magento/module-webapi/Controller/Soap.php(181): Magento\Framework\Webapi\ErrorProcessor\Proxy->maskException(Object(LogicException))
#3 /var/www/html/web/magento2test/vendor/magento/module-webapi/Controller/Soap.php(148): Magento\Webapi\Controller\Soap->_prepareErrorResponse(Object(LogicException))
#4 /var/www/html/web/magento2test/var/generation/Magento/Webapi/Controller/Soap/Interceptor.php(24): Magento\Webapi\Controller\Soap->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/web/magento2test/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Soap\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/html/web/magento2test/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#7 /var/www/html/web/magento2test/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#8 {main} [] []
```

This error stops occurring if I disable the Swarming_SubscribePro module and re-attempt to load the `https://{DOMAIN}/soap/default/?wsdl&services=catalogProductRepositoryV1` URL.

**Comment by lalitmalav** [comment]
Hi garthbrantley,

could you Please share , where did you change ?? mixed[] and string[] instead of array.

**Comment by imkingdavid** [comment]
@lalitmalav 
Many of these changes were made in our PHP SDK (https://github.com/subscribepro/subscribepro-php), which is used by this extension for API calls to the Subscribe Pro platform. For instance, you can see these commits, which are related to this issue:
https://github.com/subscribepro/subscribepro-php/commit/eb8c24c9e3c794312eb2421569e7295b6ca54624
https://github.com/subscribepro/subscribepro-php/commit/4c110f387c9f0396291b68003831cf5ab0c125fd

We recommend you make sure you are up to date with the latest version of our extension to take advantage of the latest bug fixes and improvements.

If you are still seeing issues with return types once up to date, please reach out to support@subscribepro.com with more details so that we can assist you.
