### ISSUE TITLE
Does not work for "compiled" version of Magento - Uncaught TypeError: Argument 1 passed to SubscribePro\Sdk::__construct() must be of the type array, object given

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#3]
It seems the module does not actually work for "compiled" version of Magento.
Here's the error stack

2016/10/11 09:27:42 [error] 27728#27728: *188448 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SubscribePro\Sdk::__construct() must be of the type array, object given, called in /data/www/html/intelligentsia-qa.smarterspecies.com/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /data/www/html/intelligentsia-qa.smarterspecies.com/htdocs/vendor/subscribepro/subscribepro-php/src/SubscribePro/Sdk.php:89
Stack trace:
#0 /data/www/html/intelligentsia-qa.smarterspecies.com/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): SubscribePro\Sdk->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /data/www/html/intelligentsia-qa.smarterspecies.com/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('SubscribePro\\Sd...', Array)
#2 /data/www/html/intelligentsia-qa.smarterspecies.com/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magent" while reading response header from upstream, client: 52.39.241.224, server: intelligentsia-qa.smarterspecies.com, request: "GET /checkout/cart/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "intelligentsia-qa.smarterspecies.com", referrer: "https://intelligentsia-qa.smarterspecies.com/flecha-roja-costa-rica-test"
I was able to reproduce this on my local instance with compilation performed. The module works fine in "developer" mode.

**Comment by garthbrantley** [comment]
A suggestion on how to resolve:

That makes sense - I can see that your "subscribepro-php" package is a general SDK-like php library.
In that case however in you should not use M2 Object Manager to instantiate \SubscribePro\Sdk class - nor explicitly, nor implicitly through the usage of M2 Factory pattern.
You do however require "\SubscribePro\SdkFactory" in multiple places which results in next class generated:
```
<?php
namespace SubscribePro;

/**
 * Factory class for @see \SubscribePro\Sdk
 */
class SdkFactory
{
    /**
     * Object Manager instance
     *
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $_objectManager = null;

    /**
     * Instance name to create
     *
     * @var string
     */
    protected $_instanceName = null;

    /**
     * Factory constructor
     *
     * @param \Magento\Framework\ObjectManagerInterface $objectManager
     * @param string $instanceName
     */
    public function __construct(\Magento\Framework\ObjectManagerInterface $objectManager, $instanceName = '\\SubscribePro\\Sdk')
    {
        $this->_objectManager = $objectManager;
        $this->_instanceName = $instanceName;
    }

    /**
     * Create class instance with specified parameters
     *
     * @param array $data
     * @return \SubscribePro\Sdk
     */
    public function create(array $data = array())
    {
        return $this->_objectManager->create($this->_instanceName, $data);
    }
}

```

**Comment by garthbrantley** [comment]
Another suggestion was submitted:
Another quick and simple solution that we've come up with is to explicitly define VirtualType for SubscribePro\Sdk in "Swarming_SubscribePro" di.xml config. That will allow you to leave all the places with Factory untouched.
