### ISSUE TITLE
No such entity with email = xxx, websiteId = 1

### ISSUE THREAD

**Issue by yrudiuk** [subscribepro/subscribepro-magento2-ext#40]
SP ver. 1.0.17
We've noticed an exception thrown in admin during order create process:

```
[2017-07-31 08:29:30] report.CRITICAL: exception 'Magento\Framework\Exception\NoSuchEntityException' with message 'No such entity with email = xxx, websiteId = 1' in /home/dev/projects/local.rxbar.com/www/vendor/magento/module-customer/Model/CustomerRegistry.php:121
Stack trace:
#0 /xxx/www/vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php(237): Magento\Customer\Model\CustomerRegistry->retrieveByEmail('xx...', NULL)
#1 /xxx/www/var/generation/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php(37): Magento\Customer\Model\ResourceModel\CustomerRepository->get('xx...', NULL)
#2 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Platform/Manager/Customer.php(66): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->get('xx...', NULL)
#3 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Platform/Manager/Customer.php(45): Swarming\SubscribePro\Platform\Manager\Customer->getCustomer('xx...', true, NULL)
#4 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Gateway/Command/AbstractProfileCreatorCommand.php(69): Swarming\SubscribePro\Platform\Manager\Customer->getCustomerById(82749, true)
#5 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Gateway/Command/PurchaseCommand.php(29): Swarming\SubscribePro\Gateway\Command\AbstractProfileCreatorCommand->createProfile(Array)
#6 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Gateway/Command/AbstractCommand.php(99): Swarming\SubscribePro\Gateway\Command\PurchaseCommand->processTransaction(Array)
#7 /xxx/www/vendor/subscribepro/subscribepro-magento2-ext/Gateway/Command/CaptureStrategyCommand.php(49): Swarming\SubscribePro\Gateway\Command\AbstractCommand->execute(Array)
#8 /xxx/www/vendor/magento/module-payment/Model/Method/Adapter.php(530): Swarming\SubscribePro\Gateway\Command\CaptureStrategyCommand->execute(Array)
#9 /xxx/www/vendor/magento/module-payment/Model/Method/Adapter.php(446): Magento\Payment\Model\Method\Adapter->executeCommand('capture', Array)
#10 /xxx/www/var/generation/Magento/Payment/Model/Method/Adapter/Interceptor.php(362): Magento\Payment\Model\Method\Adapter->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), '33.46')
#11 /xxx/www/vendor/magento/module-sales/Model/Order/Payment/Operations/CaptureOperation.php(82): Magento\Payment\Model\Method\Adapter\Interceptor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), '33.46')
#12 /xxx/www/vendor/magento/module-sales/Model/Order/Payment/Processor.php(85): Magento\Sales\Model\Order\Payment\Operations\CaptureOperation->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice\Interceptor))
#13 /xxx/www/vendor/magento/module-sales/Model/Order/Payment.php(447): Magento\Sales\Model\Order\Payment\Processor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice\Interceptor))
#14 /xxx/www/var/generation/Magento/Sales/Model/Order/Payment/Interceptor.php(180): Magento\Sales\Model\Order\Payment->capture(Object(Magento\Sales\Model\Order\Invoice\Interceptor))
#15 /xxx/www/vendor/magento/module-sales/Model/Order/Invoice.php(342): Magento\Sales\Model\Order\Payment\Interceptor->capture(Object(Magento\Sales\Model\Order\Invoice\Interceptor))
#16 /xxx/www/var/generation/Magento/Sales/Model/Order/Invoice/Interceptor.php(193): Magento\Sales\Model\Order\Invoice->capture()
#17 /xxx/www/vendor/magento/module-sales/Model/Order/Payment/Operations/AbstractOperation.php(70): Magento\Sales\Model\Order\Invoice\Interceptor->capture()
#18 /xxx/www/vendor/magento/module-sales/Model/Order/Payment/Operations/CaptureOperation.php(30): Magento\Sales\Model\Order\Payment\Operations\AbstractOperation->invoice(Object(Magento\Sales\Model\Order\Payment\Interceptor))
#19 /xxx/www/vendor/magento/module-sales/Model/Order/Payment/Processor.php(85): Magento\Sales\Model\Order\Payment\Operations\CaptureOperation->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), NULL)
#20 /xxx/www/vendor/magento/module-sales/Model/Order/Payment.php(447): Magento\Sales\Model\Order\Payment\Processor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), NULL)
#21 /xxx/www/var/generation/Magento/Sales/Model/Order/Payment/Interceptor.php(180): Magento\Sales\Model\Order\Payment->capture(NULL)
#22 /xxx/www/vendor/magento/module-sales/Model/Order/Payment.php(428): Magento\Sales\Model\Order\Payment\Interceptor->capture(NULL)
#23 /xxx/www/vendor/magento/module-sales/Model/Order/Payment.php(348): Magento\Sales\Model\Order\Payment->processAction('authorize_captu...', Object(Magento\Sales\Model\Order\Interceptor))
#24 /xxx/www/var/generation/Magento/Sales/Model/Order/Payment/Interceptor.php(167): Magento\Sales\Model\Order\Payment->place()
#25 /xxx/www/vendor/magento/module-sales/Model/Order.php(871): Magento\Sales\Model\Order\Payment\Interceptor->place()
#26 /xxx/www/vendor/magento/module-sales/Model/Order.php(1060): Magento\Sales\Model\Order->_placePayment()
#27 /xxx/www/var/generation/Magento/Sales/Model/Order/Interceptor.php(479): Magento\Sales\Model\Order->place()
#28 /xxx/www/vendor/magento/module-sales/Model/Service/OrderService.php(190): Magento\Sales\Model\Order\Interceptor->place()
#29 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#30 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#31 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\M...', 'place', Object(Magento\Sales\Model\Service\OrderService\Interceptor), Array, 'gorillaLockQuot...')
#32 /xxx/www/app/code/Gorilla/QuoteOrderMonitor/Plugin/Sales/OrderManagement.php(47): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#33 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(142): Gorilla\QuoteOrderMonitor\Plugin\Sales\OrderManagement->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#34 /xxx/www/var/generation/Magento/Sales/Model/Service/OrderService/Interceptor.php(117): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#35 /xxx/www/vendor/magento/module-quote/Model/QuoteManagement.php(488): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#36 /xxx/www/vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Gorilla\CorePatches\Model\Quote\Quote\Interceptor), Array)
#37 /xxx/www/vendor/magento/module-sales/Model/AdminOrder/Create.php(1875): Magento\Quote\Model\QuoteManagement->submit(Object(Gorilla\CorePatches\Model\Quote\Quote\Interceptor), Array)
#38 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Sales\Model\AdminOrder\Create->createOrder()
#39 /xxx/www/var/generation/Magento/Sales/Model/AdminOrder/Create/Interceptor.php(507): Magento\Sales\Model\AdminOrder\Create\Interceptor->___callPlugins('createOrder', Array, Array)
#40 /xxx/www/vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Save.php(49): Magento\Sales\Model\AdminOrder\Create\Interceptor->createOrder()
#41 /xxx/www/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\Create\Save->execute()
#42 /xxx/www/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->execute()
#43 /xxx/www/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent('dispatch', Array)
#46 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Array, 'adminAuthentica...')
#47 /xxx/www/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Array, 'log')
#50 /xxx/www/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#51 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Array, 'adminMassaction...')
#53 /xxx/www/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#54 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /xxx/www/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#56 /xxx/www/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#57 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#58 /xxx/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#59 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#60 /xxx/www/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#61 /xxx/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62 /xxx/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#63 /xxx/www/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#64 /xxx/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#65 /xxx/www/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
```

Issue appears on multistore, for new customer which belongs to non-default website (e.g. website id > 1).
It looks like SP doesn't pass proper website id here \Swarming\SubscribePro\Platform\Manager\Customer::getCustomer.

Thanks!

**Comment by garthbrantley** [comment]
Was previously reported as "No such entity with email = xxx, websiteId = 1"
